app: podinfo
replicas: 1

image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: 6.1.4
  pullPolicy: IfNotPresent

ui:
  message: "FluxCD <> Unbxd"

service:
  enabled: true
  type: ClusterIP
  httpPort: 9898
  port: 80 

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 64Mi

